package prueba;

// Generated 23-jul-2015 20:36:17 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Calzada generated by hbm2java
 */
@Entity
@Table(name = "calzada")
public class Calzada implements java.io.Serializable {

	private int idCalzada;
	private String tipo;
	private String estado;
	private Set<LugarSinisestro> lugarSinisestros = new HashSet<LugarSinisestro>(
			0);

	public Calzada() {
	}

	public Calzada(int idCalzada) {
		this.idCalzada = idCalzada;
	}

	public Calzada(int idCalzada, String tipo, String estado,
			Set<LugarSinisestro> lugarSinisestros) {
		this.idCalzada = idCalzada;
		this.tipo = tipo;
		this.estado = estado;
		this.lugarSinisestros = lugarSinisestros;
	}

	@Id
	@Column(name = "idCalzada", unique = true, nullable = false)
	public int getIdCalzada() {
		return this.idCalzada;
	}

	public void setIdCalzada(int idCalzada) {
		this.idCalzada = idCalzada;
	}

	@Column(name = "tipo", length = 65535)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "estado", length = 65535)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "calzada")
	public Set<LugarSinisestro> getLugarSinisestros() {
		return this.lugarSinisestros;
	}

	public void setLugarSinisestros(Set<LugarSinisestro> lugarSinisestros) {
		this.lugarSinisestros = lugarSinisestros;
	}

}
