package prueba;

// Generated 23-jul-2015 20:36:17 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Carnet generated by hbm2java
 */
@Entity
@Table(name = "carnet")
public class Carnet implements java.io.Serializable {

	private int idCarnet;
	private Date fechaVenc;
	private Set<DatosConductor> datosConductors = new HashSet<DatosConductor>(0);
	private Set<ConductorOtro> conductorOtros = new HashSet<ConductorOtro>(0);

	public Carnet() {
	}

	public Carnet(int idCarnet) {
		this.idCarnet = idCarnet;
	}

	public Carnet(int idCarnet, Date fechaVenc,
			Set<DatosConductor> datosConductors,
			Set<ConductorOtro> conductorOtros) {
		this.idCarnet = idCarnet;
		this.fechaVenc = fechaVenc;
		this.datosConductors = datosConductors;
		this.conductorOtros = conductorOtros;
	}

	@Id
	@Column(name = "idCarnet", unique = true, nullable = false)
	public int getIdCarnet() {
		return this.idCarnet;
	}

	public void setIdCarnet(int idCarnet) {
		this.idCarnet = idCarnet;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_venc", length = 10)
	public Date getFechaVenc() {
		return this.fechaVenc;
	}

	public void setFechaVenc(Date fechaVenc) {
		this.fechaVenc = fechaVenc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carnet")
	public Set<DatosConductor> getDatosConductors() {
		return this.datosConductors;
	}

	public void setDatosConductors(Set<DatosConductor> datosConductors) {
		this.datosConductors = datosConductors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carnet")
	public Set<ConductorOtro> getConductorOtros() {
		return this.conductorOtros;
	}

	public void setConductorOtros(Set<ConductorOtro> conductorOtros) {
		this.conductorOtros = conductorOtros;
	}

}
