package prueba;

// Generated 23-jul-2015 20:36:17 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConductorOtro generated by hbm2java
 */
@Entity
@Table(name = "conductor_otro")
public class ConductorOtro implements java.io.Serializable {

	private int idConductorOtro;
	private Carnet carnet;
	private Region region;
	private String apenom;
	private Integer dni;
	private String domicilio;
	private Integer telefono;
	private String genero;
	private String estadoCivil;
	private Date fechaNac;
	private Boolean conductorHab;
	private Set<OtroVehiculo> otroVehiculos = new HashSet<OtroVehiculo>(0);

	public ConductorOtro() {
	}

	public ConductorOtro(int idConductorOtro) {
		this.idConductorOtro = idConductorOtro;
	}

	public ConductorOtro(int idConductorOtro, Carnet carnet, Region region,
			String apenom, Integer dni, String domicilio, Integer telefono,
			String genero, String estadoCivil, Date fechaNac,
			Boolean conductorHab, Set<OtroVehiculo> otroVehiculos) {
		this.idConductorOtro = idConductorOtro;
		this.carnet = carnet;
		this.region = region;
		this.apenom = apenom;
		this.dni = dni;
		this.domicilio = domicilio;
		this.telefono = telefono;
		this.genero = genero;
		this.estadoCivil = estadoCivil;
		this.fechaNac = fechaNac;
		this.conductorHab = conductorHab;
		this.otroVehiculos = otroVehiculos;
	}

	@Id
	@Column(name = "idConductor_Otro", unique = true, nullable = false)
	public int getIdConductorOtro() {
		return this.idConductorOtro;
	}

	public void setIdConductorOtro(int idConductorOtro) {
		this.idConductorOtro = idConductorOtro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Carnet_idCarnet")
	public Carnet getCarnet() {
		return this.carnet;
	}

	public void setCarnet(Carnet carnet) {
		this.carnet = carnet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Region_idRegion")
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@Column(name = "apenom", length = 45)
	public String getApenom() {
		return this.apenom;
	}

	public void setApenom(String apenom) {
		this.apenom = apenom;
	}

	@Column(name = "dni")
	public Integer getDni() {
		return this.dni;
	}

	public void setDni(Integer dni) {
		this.dni = dni;
	}

	@Column(name = "domicilio", length = 45)
	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	@Column(name = "telefono")
	public Integer getTelefono() {
		return this.telefono;
	}

	public void setTelefono(Integer telefono) {
		this.telefono = telefono;
	}

	@Column(name = "genero", length = 45)
	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	@Column(name = "estado_civil", length = 45)
	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nac", length = 10)
	public Date getFechaNac() {
		return this.fechaNac;
	}

	public void setFechaNac(Date fechaNac) {
		this.fechaNac = fechaNac;
	}

	@Column(name = "conductor_hab")
	public Boolean getConductorHab() {
		return this.conductorHab;
	}

	public void setConductorHab(Boolean conductorHab) {
		this.conductorHab = conductorHab;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conductorOtro")
	public Set<OtroVehiculo> getOtroVehiculos() {
		return this.otroVehiculos;
	}

	public void setOtroVehiculos(Set<OtroVehiculo> otroVehiculos) {
		this.otroVehiculos = otroVehiculos;
	}

}
