package prueba;

// Generated 23-jul-2015 20:36:17 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CruceTren generated by hbm2java
 */
@Entity
@Table(name = "cruce_tren")
public class CruceTren implements java.io.Serializable {

	private int idCruceTren;
	private Boolean cruceTren;
	private Boolean barrera;
	private Boolean cruceSenial;
	private String estadoBarrera;
	private Set<LugarSinisestro> lugarSinisestros = new HashSet<LugarSinisestro>(
			0);

	public CruceTren() {
	}

	public CruceTren(int idCruceTren) {
		this.idCruceTren = idCruceTren;
	}

	public CruceTren(int idCruceTren, Boolean cruceTren, Boolean barrera,
			Boolean cruceSenial, String estadoBarrera,
			Set<LugarSinisestro> lugarSinisestros) {
		this.idCruceTren = idCruceTren;
		this.cruceTren = cruceTren;
		this.barrera = barrera;
		this.cruceSenial = cruceSenial;
		this.estadoBarrera = estadoBarrera;
		this.lugarSinisestros = lugarSinisestros;
	}

	@Id
	@Column(name = "idCruce_tren", unique = true, nullable = false)
	public int getIdCruceTren() {
		return this.idCruceTren;
	}

	public void setIdCruceTren(int idCruceTren) {
		this.idCruceTren = idCruceTren;
	}

	@Column(name = "cruce_tren")
	public Boolean getCruceTren() {
		return this.cruceTren;
	}

	public void setCruceTren(Boolean cruceTren) {
		this.cruceTren = cruceTren;
	}

	@Column(name = "barrera")
	public Boolean getBarrera() {
		return this.barrera;
	}

	public void setBarrera(Boolean barrera) {
		this.barrera = barrera;
	}

	@Column(name = "cruce_senial")
	public Boolean getCruceSenial() {
		return this.cruceSenial;
	}

	public void setCruceSenial(Boolean cruceSenial) {
		this.cruceSenial = cruceSenial;
	}

	@Column(name = "estado_barrera", length = 45)
	public String getEstadoBarrera() {
		return this.estadoBarrera;
	}

	public void setEstadoBarrera(String estadoBarrera) {
		this.estadoBarrera = estadoBarrera;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cruceTren")
	public Set<LugarSinisestro> getLugarSinisestros() {
		return this.lugarSinisestros;
	}

	public void setLugarSinisestros(Set<LugarSinisestro> lugarSinisestros) {
		this.lugarSinisestros = lugarSinisestros;
	}

}
