package prueba;

// Generated 23-jul-2015 20:36:17 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatosConductor generated by hbm2java
 */
@Entity
@Table(name = "datos_conductor")
public class DatosConductor implements java.io.Serializable {

	private int idDatosConductor;
	private Carnet carnet;
	private Region region;
	private String apenom;
	private int edad;
	private String genero;
	private int dni;
	private String domicilio;
	private String estadoCivil;
	private String examenAlcohol;
	private Boolean conductorHab;
	private Boolean propioAsegurado;
	private String relAsegurado;
	private Date fechaNac;
	private Set<Formulario> formularios = new HashSet<Formulario>(0);

	public DatosConductor() {
	}

	public DatosConductor(int idDatosConductor, Carnet carnet, Region region,
			String apenom, int edad, String genero, int dni, String domicilio,
			String estadoCivil, Date fechaNac) {
		this.idDatosConductor = idDatosConductor;
		this.carnet = carnet;
		this.region = region;
		this.apenom = apenom;
		this.edad = edad;
		this.genero = genero;
		this.dni = dni;
		this.domicilio = domicilio;
		this.estadoCivil = estadoCivil;
		this.fechaNac = fechaNac;
	}

	public DatosConductor(int idDatosConductor, Carnet carnet, Region region,
			String apenom, int edad, String genero, int dni, String domicilio,
			String estadoCivil, String examenAlcohol, Boolean conductorHab,
			Boolean propioAsegurado, String relAsegurado, Date fechaNac,
			Set<Formulario> formularios) {
		this.idDatosConductor = idDatosConductor;
		this.carnet = carnet;
		this.region = region;
		this.apenom = apenom;
		this.edad = edad;
		this.genero = genero;
		this.dni = dni;
		this.domicilio = domicilio;
		this.estadoCivil = estadoCivil;
		this.examenAlcohol = examenAlcohol;
		this.conductorHab = conductorHab;
		this.propioAsegurado = propioAsegurado;
		this.relAsegurado = relAsegurado;
		this.fechaNac = fechaNac;
		this.formularios = formularios;
	}

	@Id
	@Column(name = "idDatos_Conductor", unique = true, nullable = false)
	public int getIdDatosConductor() {
		return this.idDatosConductor;
	}

	public void setIdDatosConductor(int idDatosConductor) {
		this.idDatosConductor = idDatosConductor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Carnet_idCarnet", nullable = false)
	public Carnet getCarnet() {
		return this.carnet;
	}

	public void setCarnet(Carnet carnet) {
		this.carnet = carnet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Region_idRegion", nullable = false)
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@Column(name = "apenom", nullable = false, length = 45)
	public String getApenom() {
		return this.apenom;
	}

	public void setApenom(String apenom) {
		this.apenom = apenom;
	}

	@Column(name = "edad", nullable = false)
	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

	@Column(name = "genero", nullable = false, length = 45)
	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	@Column(name = "dni", nullable = false)
	public int getDni() {
		return this.dni;
	}

	public void setDni(int dni) {
		this.dni = dni;
	}

	@Column(name = "domicilio", nullable = false, length = 45)
	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	@Column(name = "estado_civil", nullable = false, length = 45)
	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	@Column(name = "examen_alcohol", length = 45)
	public String getExamenAlcohol() {
		return this.examenAlcohol;
	}

	public void setExamenAlcohol(String examenAlcohol) {
		this.examenAlcohol = examenAlcohol;
	}

	@Column(name = "conductor_hab")
	public Boolean getConductorHab() {
		return this.conductorHab;
	}

	public void setConductorHab(Boolean conductorHab) {
		this.conductorHab = conductorHab;
	}

	@Column(name = "propio_asegurado")
	public Boolean getPropioAsegurado() {
		return this.propioAsegurado;
	}

	public void setPropioAsegurado(Boolean propioAsegurado) {
		this.propioAsegurado = propioAsegurado;
	}

	@Column(name = "rel_asegurado", length = 45)
	public String getRelAsegurado() {
		return this.relAsegurado;
	}

	public void setRelAsegurado(String relAsegurado) {
		this.relAsegurado = relAsegurado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nac", nullable = false, length = 10)
	public Date getFechaNac() {
		return this.fechaNac;
	}

	public void setFechaNac(Date fechaNac) {
		this.fechaNac = fechaNac;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "datosConductor")
	public Set<Formulario> getFormularios() {
		return this.formularios;
	}

	public void setFormularios(Set<Formulario> formularios) {
		this.formularios = formularios;
	}

}
