package prueba;

// Generated 23-jul-2015 20:36:17 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DatosAsegurado generated by hbm2java
 */
@Entity
@Table(name = "datos_asegurado")
public class DatosAsegurado implements java.io.Serializable {

	private int idAsegurado;
	private Region region;
	private String apenom;
	private Integer dni;
	private String domicilio;
	private String telefono;
	private Set<Formulario> formularios = new HashSet<Formulario>(0);

	public DatosAsegurado() {
	}

	public DatosAsegurado(int idAsegurado, Region region) {
		this.idAsegurado = idAsegurado;
		this.region = region;
	}

	public DatosAsegurado(int idAsegurado, Region region, String apenom,
			Integer dni, String domicilio, String telefono,
			Set<Formulario> formularios) {
		this.idAsegurado = idAsegurado;
		this.region = region;
		this.apenom = apenom;
		this.dni = dni;
		this.domicilio = domicilio;
		this.telefono = telefono;
		this.formularios = formularios;
	}

	@Id
	@Column(name = "idAsegurado", unique = true, nullable = false)
	public int getIdAsegurado() {
		return this.idAsegurado;
	}

	public void setIdAsegurado(int idAsegurado) {
		this.idAsegurado = idAsegurado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Region_idRegion", nullable = false)
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@Column(name = "apenom", length = 45)
	public String getApenom() {
		return this.apenom;
	}

	public void setApenom(String apenom) {
		this.apenom = apenom;
	}

	@Column(name = "dni")
	public Integer getDni() {
		return this.dni;
	}

	public void setDni(Integer dni) {
		this.dni = dni;
	}

	@Column(name = "domicilio", length = 45)
	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	@Column(name = "telefono", length = 45)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "datosAsegurado")
	public Set<Formulario> getFormularios() {
		return this.formularios;
	}

	public void setFormularios(Set<Formulario> formularios) {
		this.formularios = formularios;
	}

}
