package prueba;

// Generated 23-jul-2015 20:36:17 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Formulario generated by hbm2java
 */
@Entity
@Table(name = "formulario")
public class Formulario implements java.io.Serializable {

	private int idFormulario;
	private DatosAsegurado datosAsegurado;
	private Denunciante denunciante;
	private DatosConductor datosConductor;
	private SiniestroTiempo siniestroTiempo;
	private Movil movil;
	private LugarSinisestro lugarSinisestro;
	private OtroVehiculo otroVehiculo;
	private String aseguradora;
	private Integer numPoliza;
	private Integer numSiniestro;
	private Date fecha;
	private String aclaracion;
	private String firma;
	private String detalles;

	public Formulario() {
	}

	public Formulario(int idFormulario, DatosAsegurado datosAsegurado,
			Denunciante denunciante, DatosConductor datosConductor,
			SiniestroTiempo siniestroTiempo, Movil movil,
			LugarSinisestro lugarSinisestro, OtroVehiculo otroVehiculo) {
		this.idFormulario = idFormulario;
		this.datosAsegurado = datosAsegurado;
		this.denunciante = denunciante;
		this.datosConductor = datosConductor;
		this.siniestroTiempo = siniestroTiempo;
		this.movil = movil;
		this.lugarSinisestro = lugarSinisestro;
		this.otroVehiculo = otroVehiculo;
	}

	public Formulario(int idFormulario, DatosAsegurado datosAsegurado,
			Denunciante denunciante, DatosConductor datosConductor,
			SiniestroTiempo siniestroTiempo, Movil movil,
			LugarSinisestro lugarSinisestro, OtroVehiculo otroVehiculo,
			String aseguradora, Integer numPoliza, Integer numSiniestro,
			Date fecha, String aclaracion, String firma, String detalles) {
		this.idFormulario = idFormulario;
		this.datosAsegurado = datosAsegurado;
		this.denunciante = denunciante;
		this.datosConductor = datosConductor;
		this.siniestroTiempo = siniestroTiempo;
		this.movil = movil;
		this.lugarSinisestro = lugarSinisestro;
		this.otroVehiculo = otroVehiculo;
		this.aseguradora = aseguradora;
		this.numPoliza = numPoliza;
		this.numSiniestro = numSiniestro;
		this.fecha = fecha;
		this.aclaracion = aclaracion;
		this.firma = firma;
		this.detalles = detalles;
	}

	@Id
	@Column(name = "idFormulario", unique = true, nullable = false)
	public int getIdFormulario() {
		return this.idFormulario;
	}

	public void setIdFormulario(int idFormulario) {
		this.idFormulario = idFormulario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Datos_Asegurado_idAsegurado", nullable = false)
	public DatosAsegurado getDatosAsegurado() {
		return this.datosAsegurado;
	}

	public void setDatosAsegurado(DatosAsegurado datosAsegurado) {
		this.datosAsegurado = datosAsegurado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Denunciante_idDenunciante", nullable = false)
	public Denunciante getDenunciante() {
		return this.denunciante;
	}

	public void setDenunciante(Denunciante denunciante) {
		this.denunciante = denunciante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Datos_Conductor_idDatos_Conductor", nullable = false)
	public DatosConductor getDatosConductor() {
		return this.datosConductor;
	}

	public void setDatosConductor(DatosConductor datosConductor) {
		this.datosConductor = datosConductor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Siniestro_Tiempo_idSinistro", nullable = false)
	public SiniestroTiempo getSiniestroTiempo() {
		return this.siniestroTiempo;
	}

	public void setSiniestroTiempo(SiniestroTiempo siniestroTiempo) {
		this.siniestroTiempo = siniestroTiempo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Movil_tuc", nullable = false)
	public Movil getMovil() {
		return this.movil;
	}

	public void setMovil(Movil movil) {
		this.movil = movil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Lugar_Sinisestro_idLugar_Sinisestro", nullable = false)
	public LugarSinisestro getLugarSinisestro() {
		return this.lugarSinisestro;
	}

	public void setLugarSinisestro(LugarSinisestro lugarSinisestro) {
		this.lugarSinisestro = lugarSinisestro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Otro_Vehiculo_idOtro_Vehiculo", nullable = false)
	public OtroVehiculo getOtroVehiculo() {
		return this.otroVehiculo;
	}

	public void setOtroVehiculo(OtroVehiculo otroVehiculo) {
		this.otroVehiculo = otroVehiculo;
	}

	@Column(name = "aseguradora", length = 45)
	public String getAseguradora() {
		return this.aseguradora;
	}

	public void setAseguradora(String aseguradora) {
		this.aseguradora = aseguradora;
	}

	@Column(name = "num_poliza")
	public Integer getNumPoliza() {
		return this.numPoliza;
	}

	public void setNumPoliza(Integer numPoliza) {
		this.numPoliza = numPoliza;
	}

	@Column(name = "num_siniestro")
	public Integer getNumSiniestro() {
		return this.numSiniestro;
	}

	public void setNumSiniestro(Integer numSiniestro) {
		this.numSiniestro = numSiniestro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "aclaracion", length = 45)
	public String getAclaracion() {
		return this.aclaracion;
	}

	public void setAclaracion(String aclaracion) {
		this.aclaracion = aclaracion;
	}

	@Column(name = "firma", length = 45)
	public String getFirma() {
		return this.firma;
	}

	public void setFirma(String firma) {
		this.firma = firma;
	}

	@Column(name = "detalles", length = 65535)
	public String getDetalles() {
		return this.detalles;
	}

	public void setDetalles(String detalles) {
		this.detalles = detalles;
	}

}
