package prueba;

// Generated 23-jul-2015 20:36:17 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Localidad generated by hbm2java
 */
@Entity
@Table(name = "localidad")
public class Localidad implements java.io.Serializable {

	private int idLocalidad;
	private String nombre;
	private Set<Region> regions = new HashSet<Region>(0);

	public Localidad() {
	}

	public Localidad(int idLocalidad) {
		this.idLocalidad = idLocalidad;
	}

	public Localidad(int idLocalidad, String nombre, Set<Region> regions) {
		this.idLocalidad = idLocalidad;
		this.nombre = nombre;
		this.regions = regions;
	}

	@Id
	@Column(name = "idLocalidad", unique = true, nullable = false)
	public int getIdLocalidad() {
		return this.idLocalidad;
	}

	public void setIdLocalidad(int idLocalidad) {
		this.idLocalidad = idLocalidad;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "localidad")
	public Set<Region> getRegions() {
		return this.regions;
	}

	public void setRegions(Set<Region> regions) {
		this.regions = regions;
	}

}
