package prueba;

// Generated 23-jul-2015 20:36:17 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LugarSinisestro generated by hbm2java
 */
@Entity
@Table(name = "lugar_sinisestro")
public class LugarSinisestro implements java.io.Serializable {

	private int idLugarSinisestro;
	private CruceTren cruceTren;
	private Calzada calzada;
	private Semaforo semaforo;
	private Region region;
	private Ruta ruta;
	private String interseccion;
	private String calle;
	private Set<Formulario> formularios = new HashSet<Formulario>(0);

	public LugarSinisestro() {
	}

	public LugarSinisestro(int idLugarSinisestro, Region region) {
		this.idLugarSinisestro = idLugarSinisestro;
		this.region = region;
	}

	public LugarSinisestro(int idLugarSinisestro, CruceTren cruceTren,
			Calzada calzada, Semaforo semaforo, Region region, Ruta ruta,
			String interseccion, String calle, Set<Formulario> formularios) {
		this.idLugarSinisestro = idLugarSinisestro;
		this.cruceTren = cruceTren;
		this.calzada = calzada;
		this.semaforo = semaforo;
		this.region = region;
		this.ruta = ruta;
		this.interseccion = interseccion;
		this.calle = calle;
		this.formularios = formularios;
	}

	@Id
	@Column(name = "idLugar_Sinisestro", unique = true, nullable = false)
	public int getIdLugarSinisestro() {
		return this.idLugarSinisestro;
	}

	public void setIdLugarSinisestro(int idLugarSinisestro) {
		this.idLugarSinisestro = idLugarSinisestro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Cruce_tren_idCruce_tren")
	public CruceTren getCruceTren() {
		return this.cruceTren;
	}

	public void setCruceTren(CruceTren cruceTren) {
		this.cruceTren = cruceTren;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Calzada_idCalzada")
	public Calzada getCalzada() {
		return this.calzada;
	}

	public void setCalzada(Calzada calzada) {
		this.calzada = calzada;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Semaforo_idSemaforo")
	public Semaforo getSemaforo() {
		return this.semaforo;
	}

	public void setSemaforo(Semaforo semaforo) {
		this.semaforo = semaforo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Region_idRegion", nullable = false)
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ruta_idRuta")
	public Ruta getRuta() {
		return this.ruta;
	}

	public void setRuta(Ruta ruta) {
		this.ruta = ruta;
	}

	@Column(name = "interseccion", length = 200)
	public String getInterseccion() {
		return this.interseccion;
	}

	public void setInterseccion(String interseccion) {
		this.interseccion = interseccion;
	}

	@Column(name = "calle", length = 200)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lugarSinisestro")
	public Set<Formulario> getFormularios() {
		return this.formularios;
	}

	public void setFormularios(Set<Formulario> formularios) {
		this.formularios = formularios;
	}

}
