package prueba;

// Generated 23-jul-2015 20:36:17 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Modelo generated by hbm2java
 */
@Entity
@Table(name = "modelo")
public class Modelo implements java.io.Serializable {

	private int idModelo;
	private String nombre;
	private Set<Movil> movils = new HashSet<Movil>(0);

	public Modelo() {
	}

	public Modelo(int idModelo, String nombre) {
		this.idModelo = idModelo;
		this.nombre = nombre;
	}

	public Modelo(int idModelo, String nombre, Set<Movil> movils) {
		this.idModelo = idModelo;
		this.nombre = nombre;
		this.movils = movils;
	}

	@Id
	@Column(name = "idModelo", unique = true, nullable = false)
	public int getIdModelo() {
		return this.idModelo;
	}

	public void setIdModelo(int idModelo) {
		this.idModelo = idModelo;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelo")
	public Set<Movil> getMovils() {
		return this.movils;
	}

	public void setMovils(Set<Movil> movils) {
		this.movils = movils;
	}

}
