package prueba;

// Generated 23-jul-2015 20:36:17 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Movil generated by hbm2java
 */
@Entity
@Table(name = "movil")
public class Movil implements java.io.Serializable {

	private int tuc;
	private Marca marca;
	private Tipo tipo;
	private Modelo modelo;
	private int numChasis;
	private int numMotor;
	private int numPatente;
	private String observacion;
	private Date anio;
	private Set<Formulario> formularios = new HashSet<Formulario>(0);

	public Movil() {
	}

	public Movil(int tuc, Marca marca, Tipo tipo, Modelo modelo, int numChasis,
			int numMotor, int numPatente, Date anio) {
		this.tuc = tuc;
		this.marca = marca;
		this.tipo = tipo;
		this.modelo = modelo;
		this.numChasis = numChasis;
		this.numMotor = numMotor;
		this.numPatente = numPatente;
		this.anio = anio;
	}

	public Movil(int tuc, Marca marca, Tipo tipo, Modelo modelo, int numChasis,
			int numMotor, int numPatente, String observacion, Date anio,
			Set<Formulario> formularios) {
		this.tuc = tuc;
		this.marca = marca;
		this.tipo = tipo;
		this.modelo = modelo;
		this.numChasis = numChasis;
		this.numMotor = numMotor;
		this.numPatente = numPatente;
		this.observacion = observacion;
		this.anio = anio;
		this.formularios = formularios;
	}

	@Id
	@Column(name = "tuc", unique = true, nullable = false)
	public int getTuc() {
		return this.tuc;
	}

	public void setTuc(int tuc) {
		this.tuc = tuc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Marca_idMarca", nullable = false)
	public Marca getMarca() {
		return this.marca;
	}

	public void setMarca(Marca marca) {
		this.marca = marca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Tipo_idTipo", nullable = false)
	public Tipo getTipo() {
		return this.tipo;
	}

	public void setTipo(Tipo tipo) {
		this.tipo = tipo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Modelo_idModelo", nullable = false)
	public Modelo getModelo() {
		return this.modelo;
	}

	public void setModelo(Modelo modelo) {
		this.modelo = modelo;
	}

	@Column(name = "num_chasis", nullable = false)
	public int getNumChasis() {
		return this.numChasis;
	}

	public void setNumChasis(int numChasis) {
		this.numChasis = numChasis;
	}

	@Column(name = "num_motor", nullable = false)
	public int getNumMotor() {
		return this.numMotor;
	}

	public void setNumMotor(int numMotor) {
		this.numMotor = numMotor;
	}

	@Column(name = "num_patente", nullable = false)
	public int getNumPatente() {
		return this.numPatente;
	}

	public void setNumPatente(int numPatente) {
		this.numPatente = numPatente;
	}

	@Column(name = "observacion", length = 65535)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "anio", nullable = false, length = 10)
	public Date getAnio() {
		return this.anio;
	}

	public void setAnio(Date anio) {
		this.anio = anio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movil")
	public Set<Formulario> getFormularios() {
		return this.formularios;
	}

	public void setFormularios(Set<Formulario> formularios) {
		this.formularios = formularios;
	}

}
