package prueba;

// Generated 23-jul-2015 20:36:17 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OtroVehiculo generated by hbm2java
 */
@Entity
@Table(name = "otro_vehiculo")
public class OtroVehiculo implements java.io.Serializable {

	private int idOtroVehiculo;
	private Region region;
	private ConductorOtro conductorOtro;
	private String apenom;
	private Integer edad;
	private String dni;
	private String marca;
	private String modelo;
	private String tipo;
	private String dominio;
	private Date anio;
	private Integer numMotor;
	private String numChasis;
	private String detelles;
	private Boolean usoVehiculo;
	private Integer tipoUso;
	private Integer alcoholemia;
	private Boolean propietario;
	private Set<Formulario> formularios = new HashSet<Formulario>(0);

	public OtroVehiculo() {
	}

	public OtroVehiculo(int idOtroVehiculo, Region region) {
		this.idOtroVehiculo = idOtroVehiculo;
		this.region = region;
	}

	public OtroVehiculo(int idOtroVehiculo, Region region,
			ConductorOtro conductorOtro, String apenom, Integer edad,
			String dni, String marca, String modelo, String tipo,
			String dominio, Date anio, Integer numMotor, String numChasis,
			String detelles, Boolean usoVehiculo, Integer tipoUso,
			Integer alcoholemia, Boolean propietario,
			Set<Formulario> formularios) {
		this.idOtroVehiculo = idOtroVehiculo;
		this.region = region;
		this.conductorOtro = conductorOtro;
		this.apenom = apenom;
		this.edad = edad;
		this.dni = dni;
		this.marca = marca;
		this.modelo = modelo;
		this.tipo = tipo;
		this.dominio = dominio;
		this.anio = anio;
		this.numMotor = numMotor;
		this.numChasis = numChasis;
		this.detelles = detelles;
		this.usoVehiculo = usoVehiculo;
		this.tipoUso = tipoUso;
		this.alcoholemia = alcoholemia;
		this.propietario = propietario;
		this.formularios = formularios;
	}

	@Id
	@Column(name = "idOtro_Vehiculo", unique = true, nullable = false)
	public int getIdOtroVehiculo() {
		return this.idOtroVehiculo;
	}

	public void setIdOtroVehiculo(int idOtroVehiculo) {
		this.idOtroVehiculo = idOtroVehiculo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Region_idRegion", nullable = false)
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Conductor_Otro_idConductor_Otro")
	public ConductorOtro getConductorOtro() {
		return this.conductorOtro;
	}

	public void setConductorOtro(ConductorOtro conductorOtro) {
		this.conductorOtro = conductorOtro;
	}

	@Column(name = "apenom", length = 45)
	public String getApenom() {
		return this.apenom;
	}

	public void setApenom(String apenom) {
		this.apenom = apenom;
	}

	@Column(name = "edad")
	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	@Column(name = "dni", length = 45)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@Column(name = "marca", length = 45)
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	@Column(name = "modelo", length = 45)
	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	@Column(name = "tipo", length = 45)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "dominio", length = 45)
	public String getDominio() {
		return this.dominio;
	}

	public void setDominio(String dominio) {
		this.dominio = dominio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "anio", length = 10)
	public Date getAnio() {
		return this.anio;
	}

	public void setAnio(Date anio) {
		this.anio = anio;
	}

	@Column(name = "num_motor")
	public Integer getNumMotor() {
		return this.numMotor;
	}

	public void setNumMotor(Integer numMotor) {
		this.numMotor = numMotor;
	}

	@Column(name = "num_chasis", length = 45)
	public String getNumChasis() {
		return this.numChasis;
	}

	public void setNumChasis(String numChasis) {
		this.numChasis = numChasis;
	}

	@Column(name = "detelles", length = 45)
	public String getDetelles() {
		return this.detelles;
	}

	public void setDetelles(String detelles) {
		this.detelles = detelles;
	}

	@Column(name = "uso_vehiculo")
	public Boolean getUsoVehiculo() {
		return this.usoVehiculo;
	}

	public void setUsoVehiculo(Boolean usoVehiculo) {
		this.usoVehiculo = usoVehiculo;
	}

	@Column(name = "tipo_uso")
	public Integer getTipoUso() {
		return this.tipoUso;
	}

	public void setTipoUso(Integer tipoUso) {
		this.tipoUso = tipoUso;
	}

	@Column(name = "alcoholemia")
	public Integer getAlcoholemia() {
		return this.alcoholemia;
	}

	public void setAlcoholemia(Integer alcoholemia) {
		this.alcoholemia = alcoholemia;
	}

	@Column(name = "propietario")
	public Boolean getPropietario() {
		return this.propietario;
	}

	public void setPropietario(Boolean propietario) {
		this.propietario = propietario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "otroVehiculo")
	public Set<Formulario> getFormularios() {
		return this.formularios;
	}

	public void setFormularios(Set<Formulario> formularios) {
		this.formularios = formularios;
	}

}
