package prueba;

// Generated 23-jul-2015 20:36:17 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ruta generated by hbm2java
 */
@Entity
@Table(name = "ruta")
public class Ruta implements java.io.Serializable {

	private int idRuta;
	private Integer numRuta;
	private Integer kilometro;
	private String cruceConRuta;
	private Boolean cruceSenial;
	private String tipo;
	private Set<LugarSinisestro> lugarSinisestros = new HashSet<LugarSinisestro>(
			0);

	public Ruta() {
	}

	public Ruta(int idRuta) {
		this.idRuta = idRuta;
	}

	public Ruta(int idRuta, Integer numRuta, Integer kilometro,
			String cruceConRuta, Boolean cruceSenial, String tipo,
			Set<LugarSinisestro> lugarSinisestros) {
		this.idRuta = idRuta;
		this.numRuta = numRuta;
		this.kilometro = kilometro;
		this.cruceConRuta = cruceConRuta;
		this.cruceSenial = cruceSenial;
		this.tipo = tipo;
		this.lugarSinisestros = lugarSinisestros;
	}

	@Id
	@Column(name = "idRuta", unique = true, nullable = false)
	public int getIdRuta() {
		return this.idRuta;
	}

	public void setIdRuta(int idRuta) {
		this.idRuta = idRuta;
	}

	@Column(name = "num_ruta")
	public Integer getNumRuta() {
		return this.numRuta;
	}

	public void setNumRuta(Integer numRuta) {
		this.numRuta = numRuta;
	}

	@Column(name = "kilometro")
	public Integer getKilometro() {
		return this.kilometro;
	}

	public void setKilometro(Integer kilometro) {
		this.kilometro = kilometro;
	}

	@Column(name = "cruce_con_ruta", length = 45)
	public String getCruceConRuta() {
		return this.cruceConRuta;
	}

	public void setCruceConRuta(String cruceConRuta) {
		this.cruceConRuta = cruceConRuta;
	}

	@Column(name = "cruce_senial")
	public Boolean getCruceSenial() {
		return this.cruceSenial;
	}

	public void setCruceSenial(Boolean cruceSenial) {
		this.cruceSenial = cruceSenial;
	}

	@Column(name = "tipo", length = 45)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ruta")
	public Set<LugarSinisestro> getLugarSinisestros() {
		return this.lugarSinisestros;
	}

	public void setLugarSinisestros(Set<LugarSinisestro> lugarSinisestros) {
		this.lugarSinisestros = lugarSinisestros;
	}

}
