package prueba;

// Generated 23-jul-2015 20:36:17 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Semaforo generated by hbm2java
 */
@Entity
@Table(name = "semaforo")
public class Semaforo implements java.io.Serializable {

	private int idSemaforo;
	private Boolean semaforo;
	private Boolean funciona;
	private Boolean intermitente;
	private String color;
	private Set<LugarSinisestro> lugarSinisestros = new HashSet<LugarSinisestro>(
			0);

	public Semaforo() {
	}

	public Semaforo(int idSemaforo) {
		this.idSemaforo = idSemaforo;
	}

	public Semaforo(int idSemaforo, Boolean semaforo, Boolean funciona,
			Boolean intermitente, String color,
			Set<LugarSinisestro> lugarSinisestros) {
		this.idSemaforo = idSemaforo;
		this.semaforo = semaforo;
		this.funciona = funciona;
		this.intermitente = intermitente;
		this.color = color;
		this.lugarSinisestros = lugarSinisestros;
	}

	@Id
	@Column(name = "idSemaforo", unique = true, nullable = false)
	public int getIdSemaforo() {
		return this.idSemaforo;
	}

	public void setIdSemaforo(int idSemaforo) {
		this.idSemaforo = idSemaforo;
	}

	@Column(name = "semaforo")
	public Boolean getSemaforo() {
		return this.semaforo;
	}

	public void setSemaforo(Boolean semaforo) {
		this.semaforo = semaforo;
	}

	@Column(name = "funciona")
	public Boolean getFunciona() {
		return this.funciona;
	}

	public void setFunciona(Boolean funciona) {
		this.funciona = funciona;
	}

	@Column(name = "intermitente")
	public Boolean getIntermitente() {
		return this.intermitente;
	}

	public void setIntermitente(Boolean intermitente) {
		this.intermitente = intermitente;
	}

	@Column(name = "color", length = 45)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semaforo")
	public Set<LugarSinisestro> getLugarSinisestros() {
		return this.lugarSinisestros;
	}

	public void setLugarSinisestros(Set<LugarSinisestro> lugarSinisestros) {
		this.lugarSinisestros = lugarSinisestros;
	}

}
