package prueba;

// Generated 23-jul-2015 20:36:17 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SiniestroTiempo generated by hbm2java
 */
@Entity
@Table(name = "siniestro_tiempo")
public class SiniestroTiempo implements java.io.Serializable {

	private int idSinistro;
	private Date fechaSiniestro;
	private String turno;
	private String tiempo;
	private Date hora;
	private Set<Formulario> formularios = new HashSet<Formulario>(0);

	public SiniestroTiempo() {
	}

	public SiniestroTiempo(int idSinistro, Date fechaSiniestro) {
		this.idSinistro = idSinistro;
		this.fechaSiniestro = fechaSiniestro;
	}

	public SiniestroTiempo(int idSinistro, Date fechaSiniestro, String turno,
			String tiempo, Date hora, Set<Formulario> formularios) {
		this.idSinistro = idSinistro;
		this.fechaSiniestro = fechaSiniestro;
		this.turno = turno;
		this.tiempo = tiempo;
		this.hora = hora;
		this.formularios = formularios;
	}

	@Id
	@Column(name = "idSinistro", unique = true, nullable = false)
	public int getIdSinistro() {
		return this.idSinistro;
	}

	public void setIdSinistro(int idSinistro) {
		this.idSinistro = idSinistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_siniestro", nullable = false, length = 10)
	public Date getFechaSiniestro() {
		return this.fechaSiniestro;
	}

	public void setFechaSiniestro(Date fechaSiniestro) {
		this.fechaSiniestro = fechaSiniestro;
	}

	@Column(name = "turno", length = 45)
	public String getTurno() {
		return this.turno;
	}

	public void setTurno(String turno) {
		this.turno = turno;
	}

	@Column(name = "tiempo", length = 45)
	public String getTiempo() {
		return this.tiempo;
	}

	public void setTiempo(String tiempo) {
		this.tiempo = tiempo;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora", length = 8)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "siniestroTiempo")
	public Set<Formulario> getFormularios() {
		return this.formularios;
	}

	public void setFormularios(Set<Formulario> formularios) {
		this.formularios = formularios;
	}

}
