package prueba;

// Generated 23-jul-2015 20:36:17 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipo generated by hbm2java
 */
@Entity
@Table(name = "tipo")
public class Tipo implements java.io.Serializable {

	private int idTipo;
	private String nombre;
	private Set<Movil> movils = new HashSet<Movil>(0);

	public Tipo() {
	}

	public Tipo(int idTipo, String nombre) {
		this.idTipo = idTipo;
		this.nombre = nombre;
	}

	public Tipo(int idTipo, String nombre, Set<Movil> movils) {
		this.idTipo = idTipo;
		this.nombre = nombre;
		this.movils = movils;
	}

	@Id
	@Column(name = "idTipo", unique = true, nullable = false)
	public int getIdTipo() {
		return this.idTipo;
	}

	public void setIdTipo(int idTipo) {
		this.idTipo = idTipo;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipo")
	public Set<Movil> getMovils() {
		return this.movils;
	}

	public void setMovils(Set<Movil> movils) {
		this.movils = movils;
	}

}
